development:
  adapter: <%= Settings.oracle.adapter %>
  host: <%= Settings.oracle.host %>
  port: <%= Settings.oracle.port %>
  database: <%= Settings.oracle.database %>
  username: <%= Settings.oracle.username %>
  password: <%= Settings.oracle.password %>
  pool: <%= Settings.oracle.pool %>
  timeout: <%= Settings.oracle.timeout %>
  encoding: <%= Settings.oracle.encoding %>

production:
  adapter: <%= Settings.oracle.adapter %>
  database: <%= Settings.oracle.database %>
  pool: <%= Settings.oracle.pool %>
  timeout: <%= Settings.oracle.timeout %>
  username: <%= Settings.oracle.username %>
  password: <%= Settings.oracle.password %>
  host: <%= Settings.oracle.host %>
  port: <%= Settings.oracle.port %>

test:
  adapter: sqlite3
  encoding: utf8
  database: 'db/test.sqlite3'
  pool: <%= Settings.test_sqlite.pool %>

# The places where these settings are filled out are settings.yml and production.yml
# You should only be filling in custom values and secrets within production.local.yml
campusdb:
  adapter: <%= Settings.campusdb.adapter %>
  driver: <%=Settings.campusdb.driver %>
  url: <%=Settings.campusdb.url %>
  username: <%=Settings.campusdb.username %>
  password: <%=Settings.campusdb.password %>
  pool: <%=Settings.campusdb.pool %>
  timeout: <%=Settings.campusdb.timeout %>

edodb:
  adapter: <%= Settings.edodb.adapter %>
  driver: <%=Settings.edodb.driver %>
  url: <%=Settings.edodb.url %>
  username: <%=Settings.edodb.username %>
  password: <%=Settings.edodb.password %>
  pool: <%=Settings.edodb.pool %>
  timeout: <%=Settings.edodb.timeout %>
