application:
  layer: 'development'

logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || true %>
  slow_query_threshold_in_ms: 2000

blog_latest_release_notes_feed_proxy:
  fake: true

cache:
  store: 'memory'
  log_level: <%= Logger::DEBUG %>

cal_link_proxy:
  fake: true

canvas_proxy:
  fake: true

cas_server: 'https://auth-test.berkeley.edu/cas'

cas_logout_url: 'https://auth-test.berkeley.edu/cas/logout'

financials_proxy:
  fake: true

textbooks_proxy:
  fake: true

google_proxy:
  fake: true

mailgun_proxy:
  fake: true

cal1card_proxy:
  fake: true

webcast_proxy:
  fake: true

postgres:
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] || 'calcentral_development' %>
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] || 'calcentral_development' %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] || 'secret' %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>
  pool: 3

campusdb:
  fake: true

edodb:
  fake: true

ist_jms:
  fake: true
  enabled: false

eft_proxy:
  fake: true

grading_period:
  start: 2016-12-12 0:0:0
  end: 2017-01-06 23:59:59
  assistance_link: '#'

features:
  advising: true
  advising_academic_planner: true
  advising_student_success: true
  cal1card: true
  class_info_enrollment_tab: true
  course_manage_official_sections: true
  cs_academic_planner: true
  cs_advisor_student_lookup: true
  cs_billing: true
  cs_committees: true
  cs_degree_progress_grad_advising: true
  cs_degree_progress_grad_student: true
  cs_degree_progress_ugrd_advising: true
  cs_delegated_access: true
  cs_enrollment_card: true
  cs_fin_aid: true
  cs_fin_aid_award_compare: true
  cs_logout: true
  cs_profile_emergency_contacts: true
  cs_profile_languages: true
  cs_profile_work_experience: true
  my_fin_aid: true
  prevent_acting_as_users_from_posting: false
  reauthentication: false
  textbooks: true
  videos: true

oracle:
  adapter: sqlite3
  encoding: utf8
  database: 'db/dev.sqlite3'
  username:
  password:
  host:
  port: 0
  pool: 3
  timeout: 5000
